spring:
  datasource:
    url: jdbc:mysql://localhost/bdpruebapf
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAUWV5GFUEOXQUZDOD
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
